name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - name: Build executable for release
        run: swift build -v -c release -Xswiftc -disable-round-trip-debug-types
      - run: ls -la .build/release/
      - name: Compress archive
        run: tar -czf chat.swift.${{ github.ref_name }}.tar.gz .build/release/chat.swift
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: chat.swift.${{ github.ref_name }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
